{"Appeal Number": "ITA 5/VNS/2020", "Filed By": "Assessee", "Appellant": "Indra Narayan Tripathi, Gorakhpur", "Respondent": "Assistant Commissioner of Income Tax, Range - 02,, Gorakhpur", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 43/VNS/2020", "Filed By": "Assessee", "Appellant": "Pratap Diagnostic Centre, Azamgarh", "Respondent": "ITO (TDS), Azamgarh", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 13/VNS/2020", "Filed By": "Assessee", "Appellant": "Amar Nath Yadav, Gorakhpur", "Respondent": "ITO, Ward - 01 (01), Gorakhpur", "Bench": "DB", "Case Status": "Heard", "Details": ""}
{"Appeal Number": "ITA 19/VNS/2020", "Filed By": "Assessee", "Appellant": "Purushottam Das Agrawal, Varanasi", "Respondent": "PCIT,, Varanasi", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 7/VNS/2022", "Filed By": "Assessee", "Appellant": "Pratap Diagnostic Center, Azamgarh", "Respondent": "ITO (TDS),, Azamgarh", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 8/VNS/2022", "Filed By": "Assessee", "Appellant": "Pratap Diagnostic Center, Azamgarh", "Respondent": "ITO (TDS), Azamgarh", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 2543/AHD/2015", "Filed By": "Assessee", "Appellant": "Shri  Jigneshbhai Kishorbhai Bhajiyawala ( HUF),, Surat", "Respondent": "The  Income Tax Officer, Ward-2(1),, Surat", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 2544/AHD/2015", "Filed By": "Assessee", "Appellant": "Smt. Jasmine Vilasbhai Bhajiyawala,, Surat", "Respondent": "The  Income Tax Officer, Ward-2(1),, Surat", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 2545/AHD/2015", "Filed By": "Assessee", "Appellant": "Smt. Varshaben Jigneshbhai Bhajiyawala,, Surat", "Respondent": "The  Income Tax Officer, Ward-2(1),, Surat", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 2644/AHD/2015", "Filed By": "Assessee", "Appellant": "Shri  Vilas Kishorbhai Bhajiyawala (HUF)., Surat", "Respondent": "The  Income Tax Officer, Ward-2(1),, Surat", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 327/SRT/2019", "Filed By": "Assessee", "Appellant": "Sanjay Vimal Jain, Surat", "Respondent": "ITO, Ward 2(3)(8), Surat", "Bench": "DB", "Case Status": "Heard", "Details": ""}
{"Appeal Number": "ITA 131/SRT/2021", "Filed By": "Department", "Appellant": "Assistant Commissioner of Income Tax, Cir.2(1)(1), Surat", "Respondent": "The Surat District Co-op. Bank Ltd., Surat", "Bench": "DB", "Case Status": "Heard", "Details": ""}
{"Appeal Number": "ITA 836/PUN/2018", "Filed By": "Department", "Appellant": "Deputy Commissioner of Income-tax, Circle - 14,, Pune", "Respondent": "Maharashtra State Warehousing Corporation,, Pune", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1308/PUN/2019", "Filed By": "Department", "Appellant": "Deputy Commissioner of Income-tax, Panvel Circle,, Panvel", "Respondent": "Shivbahadur Srinath Yadav,, Raigad", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1448/PUN/2019", "Filed By": "Department", "Appellant": "Deputy Commissioner of Income-tax, Circle - 14,, Pune", "Respondent": "Sunil Shivajirao Bhosale,, Pune", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 289/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 290/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 291/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 292/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 293/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 294/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 295/PUN/2021", "Filed By": "Assessee", "Appellant": "Brihans Laboratories P Ltd, Pune", "Respondent": "Principal Commissioner of Income-Tax, Range -3, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "CO 13/PUN/2022", "Filed By": "Assessee", "Appellant": "Sunil Shivajirao Bhosale,, Pune", "Respondent": "Deputy Commissioner of Income-tax, Circle - 14,, Pune", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 130/PUN/2018", "Filed By": "Department", "Appellant": "Assistant Commissioner of Income-tax, Circle - 6,, Pune", "Respondent": "M/s. Shirdi Country Inns Pvt.Ltd,, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 263/PUN/2018", "Filed By": "Assessee", "Appellant": "Raosahebdada Pawar Ghodganga Sahakari Sakhar Karkhana Ltd,, Pune", "Respondent": "Income-tax Officer, Ward - 13(5),, Pune", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1143/PUN/2018", "Filed By": "Assessee", "Appellant": "Bhima Sahakari Sakhar Karkhana LTD,, Pune", "Respondent": "Deputy Commissioner of Income-tax, Circle - 14,, Pune", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1283/PUN/2018", "Filed By": "Assessee", "Appellant": "Minilec India Pvt.Ltd,, Pune", "Respondent": "Deputy Commissioner of Income-tax, Circle - 14,, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1505/PUN/2018", "Filed By": "Assessee", "Appellant": "Kumbhi Kasari Sahakari Sakhar Karkhana Ltd,, Kolhapur", "Respondent": "Assistant Commissioner of Income-tax, Circle - 1,, Kolhapur", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1524/PUN/2018", "Filed By": "Assessee", "Appellant": "Sahakar Maharshi Shankarrao Mohite Patil SSK Ltd,, Solapur", "Respondent": "Deputy Commissioner of Income-tax, Circle - 1,, Solapur", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1774/PUN/2018", "Filed By": "Assessee", "Appellant": "Mr. Rahul Gopal Nair,, Pune", "Respondent": "Assistant Commissioner of Income-tax, Circle -2,, Pune", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1897/PUN/2018", "Filed By": "Assessee", "Appellant": "Shri. Dnyaneshwar Sahakari Sakhar Karkhana Limited,, Ahmednagar", "Respondent": "Assistant Commissioner of Income-tax, Ahmednagar Circle,, Ahmednagar", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 319/PUN/2019", "Filed By": "Assessee", "Appellant": "Deputy Collector Office,, Udgir", "Respondent": "Joint Commissioner of Income-tax, TDS Range,, Nashik", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 205/PUN/2021", "Filed By": "Assessee", "Appellant": "Shrinath Nagari Sahakari Pat Sanstha , Pune", "Respondent": "Principal Commissioner of Income-Tax -4, Pune", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 108/MUM/2022", "Filed By": "Assessee", "Appellant": "SHREE ANIRUDDHA UPASANA FOUNDATION, MUMBAI", "Respondent": "CIT (EXEMPTION), MUMBAI", "Bench": "G", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 741/MUM/2021", "Filed By": "Assessee", "Appellant": "OWENS CORNING INC. , MUMBAI", "Respondent": "THE DY CIT(INTERNATIONAL TAX)CIRCLE-3(2)(2), MUMBAI", "Bench": "I", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1014/MUM/2021", "Filed By": "Assessee", "Appellant": "ANL SINGAPORE PTE LTD., MUMBAI", "Respondent": "DY CIT (INTERNATIONAL TAXATIONA)-1(1)(2), MUMBAI", "Bench": "I", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1212/MUM/2021", "Filed By": "Assessee", "Appellant": "NTT ASIA PACIFIC HOLDINGS PTE. LTD., MUMBAI", "Respondent": "THE ASSTT. CIT (INTERNATIONAL TAXATION)-2(1)(2), MUMBAI", "Bench": "I", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 305/MUM/2017", "Filed By": "Department", "Appellant": "DCIT CEN CIR 1(2), MUMBAI", "Respondent": "GITANJALI EXPORTS CORPORATION LTD, MUMBAI", "Bench": "K", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 11/MUM/2018", "Filed By": "Department", "Appellant": "JT.COMMISSIONER OF INCOME TAX (OSD)- 14(1)(1), MUMBAI", "Respondent": "CLEARWATER CAPITAL PARTNERS INDIA PRIVATE LIMITED (NOW KNOWN AS ALTICO CAPITAL INDIA PRIVATE LIMITED, MUMBAI", "Bench": "K", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 424/MUM/2018", "Filed By": "Assessee", "Appellant": "ALTICO CAPITAL INDIA PRIVATE LIMITED ( FORMERLY CLEARWATER CAPITAL PARTNERS (I) PRIVATE LIMITED , MUMBAI", "Respondent": "ACIT CIRCLE-14(1)(2), MUMBAI", "Bench": "K", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1904/MUM/2020", "Filed By": "Assessee", "Appellant": "MR. PRAKASH J.  JAJU, MUMBAI", "Respondent": "ITO - 11(1)(3), MUMBAI", "Bench": "SMC", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1481/MUM/2021", "Filed By": "Assessee", "Appellant": "NISHRIN TRADING  & INVESTMENTS PVT. LTD, MUMBAI", "Respondent": "DCIT CENTRAL CIRCLE7(3), MUMBAI", "Bench": "SMC", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 7695/MUM/2019", "Filed By": "Department", "Appellant": "DY CIT 9 (1)(2), MUMBAI", "Respondent": "ATLANTA LIMITED, MUMBAI", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 7749/MUM/2019", "Filed By": "Assessee", "Appellant": "M/S ATLANTA LTD, MUMBAI", "Respondent": "DCIT CIRCLE- 9 (1)(2), MUMBAI", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 2101/MUM/2021", "Filed By": "Assessee", "Appellant": "ARCADIA TRAVELS PVT. LTD, MUMBAI", "Respondent": "DCIT NeAC, DELHI", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 341/MUM/2021", "Filed By": "Assessee", "Appellant": "SAPPHIRE LAND DEVELOPMENT P. LTD., MUMBAI", "Respondent": "DY CIT , CC-5(4), MUMBAI", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 347/MUM/2021", "Filed By": "Assessee", "Appellant": "M/S. SAPPHIRE LAND DEVELOPMENT P. LTD., MUMBAI", "Respondent": "DY CIT, CC-5(4), MUMBAI", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 344/MUM/2021", "Filed By": "Assessee", "Appellant": "M/S. SAPPHIRE LAND DEVELOPMENT PVT. LTD, MUMBAI", "Respondent": "DCIT CENT. CIR. 5(4) , MUMBAI", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 4144/MUM/2013", "Filed By": "Assessee", "Appellant": "REID AND TAYLOR (INDIA) LTD, MUMBAI", "Respondent": "ADDL CIT RG 4(3), MUMBAI", "Bench": "D", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1227/MUM/2019", "Filed By": "Assessee", "Appellant": "M/S RAJ OIL MILLS LTD., Mumbai", "Respondent": "ACIT CENTRAL CIRCLE-6(1), Mumbai", "Bench": "D", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 913/MUM/2021", "Filed By": "Assessee", "Appellant": "M/S. RALLIS INDIA LTD., MUMBAI", "Respondent": "DY CIT,CICLE-8(1)(1), MUMBAI", "Bench": "D", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 144/MUM/2021", "Filed By": "Assessee", "Appellant": "MICHAEL PAGE INTERNATIONAL Pte LTD., MUMBAI", "Respondent": "DY CIT (INTL. TAXN.)-3(2)(2), MUMBAI", "Bench": "I", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "SA 80/MUM/2022", "Filed By": "Assessee", "Appellant": "Nearbuy Pte.. Ltd, SINGAPORE", "Respondent": "ACIT (INTL TAX) CIRCLE 3(3) (1) , MUMBAI", "Bench": "I", "Case Status": "Heard", "Details": ""}
{"Appeal Number": "ITSSA 116/LKW/2021", "Filed By": "Assessee", "Appellant": "ANJU GOENKA, KANPUR NAGAR", "Respondent": "DEPUTY COMISSIONER OF INCOME TAX, CENTRAL CIRCLE - I, KANPUR, KANPUR", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 374/LKW/2020", "Filed By": "Department", "Appellant": "DCIT, Range-1, Lucknow", "Respondent": "M/s. U.P. Projects Corporation Ltd.,, Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 51/LKW/2021", "Filed By": "Assessee", "Appellant": "M/s Sahara Credit Cooperative Society Limited, Lucknow, Lucknow", "Respondent": "Principal Commissioner of Income Tax, Lucknow -1, Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 115/LKW/2021", "Filed By": "Assessee", "Appellant": "Rohit Gupta, Kanpur", "Respondent": "Deputy Commissioner of  Income Tax, Central Circle-II, Kanpur", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 737/LKW/2017", "Filed By": "Assessee", "Appellant": "Rajkali Mohallal Trust, Lucknow", "Respondent": "Commissioner of Income Tax (Exemption), Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 760/LKW/2017", "Filed By": "Assessee", "Appellant": "M/S. Big Brokers House Stock Limited, Kanpur", "Respondent": "Assistant Commissioner of Income Tax,C.C-II, Kanpur", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 761/LKW/2017", "Filed By": "Assessee", "Appellant": "M/S. Big Brokers House Stock Limited, Kanpur", "Respondent": "Assistant Commissioner of Income Tax,C.C-II, Kanpur", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 362/LKW/2018", "Filed By": "Assessee", "Appellant": "Shri Tejpal Singh Bhatia, Kanpur", "Respondent": "Income Tax Officer-1(5), Kanpur", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 308/LKW/2019", "Filed By": "Assessee", "Appellant": "A P S Academy, Lucknow", "Respondent": "Income Tax Officer-IV(1), Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 616/LKW/2019", "Filed By": "Department", "Appellant": "Dy. Commissioner of Income Tax, Lucknow", "Respondent": "M/s U.P Project Corp. Ltd., Lucknow", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 129/LKW/2020", "Filed By": "Department", "Appellant": "Income Tax Officer-2(5), Kanpur", "Respondent": "Shri Durga Prasad Rawat, Kanpur", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 178/LKW/2020", "Filed By": "Department", "Appellant": "Assistant Commissioner of Income Tax (E), Lucknow", "Respondent": "M/s. Maharshi Patanjali Vidya Mandir Samiti, Allahabad", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 291/LKW/2020", "Filed By": "Department", "Appellant": "DCIT, Range-1, Lucknow", "Respondent": "M/s. U.P. Projects Corporation Ltd.,, Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 331/LKW/2020", "Filed By": "Department", "Appellant": "DCIT, Range-3, Lucknow", "Respondent": "M/s. U.P. Projects Corporation Ltd.,, Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 17/LKW/2020", "Filed By": "Department", "Appellant": "Income Tax Officer- 6(3), Lucknow", "Respondent": "Shri Priyanshu Rasgogi, Lucknow", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 1/LKW/2022", "Filed By": "Department", "Appellant": "Deputy Commissioner of Income Tax, CC-I, Kanpur", "Respondent": "Miss Stuti Dalmia, Kanpur", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 2/LKW/2022", "Filed By": "Department", "Appellant": "Deputy Commissioner of Income Tax, CC-I, Kanpur", "Respondent": "Miss Stuti Dalmia, Kanpur", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 3/LKW/2022", "Filed By": "Department", "Appellant": "Deputy Commissioner of Income Tax, CC-I, Kanpur", "Respondent": "Miss Stuti Dalmia, Kanpur", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 413/KOL/2020", "Filed By": "Assessee", "Appellant": "Milk Mantra Dairy (P) Ltd., Bhubaneswar", "Respondent": "DCIT, Cir.-12(1), Kolkata", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "CO 15/KOL/2017", "Filed By": "Assessee", "Appellant": "Sasamusa Sugar Works Pvt. Ltd., Kolkata", "Respondent": "DCIT, CIR-10(2), KOLKATA, Kolkata", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 20/JPR/2020", "Filed By": "Assessee", "Appellant": "SHRI TEJENDER PAL SINGH SAHNI, KOTA", "Respondent": "DEPUTY COMMISSIONER OF INCOME TAX, CENTRAL, KOTA", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 21/JPR/2020", "Filed By": "Assessee", "Appellant": "SHRI TEJENDER PAL SINGH SAHNI, KOTA", "Respondent": "DEPUTY COMMISSIONER OF INCOME TAX, CENTRAL, KOTA", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 61/Hyd/2022", "Filed By": "Assessee", "Appellant": "Spectrum Power Generation Limited , Hyderabad", "Respondent": "Dy. Commissioner of Income Tax , Circle-3(2), Hyderabad", "Bench": "DB-A", "Case Status": "Fixed", "Details": ""}
{"Appeal Number": "CO 41/Hyd/2018", "Filed By": "Assessee", "Appellant": "Panyam Cement & Mineral Industris Limited , Nandyal", "Respondent": "Asst. Commissioner of Income Tax, Circle-1, Kurnool", "Bench": "DB-A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 8548/DEL/2019", "Filed By": "Assessee", "Appellant": "Apollo International Limited, New Delhi", "Respondent": "DCIT, Circle-3(1), New Delhi", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 6592/DEL/2019", "Filed By": "Assessee", "Appellant": "Delhi Iron & Steel Co. Ltd., Ghaziabad", "Respondent": "DCIT, Central Circle-1, Ghaziabad", "Bench": "B", "Case Status": "Heard", "Details": ""}
{"Appeal Number": "ITA 4525/DEL/2018", "Filed By": "Assessee", "Appellant": "Dr. Kamal Kumar Sethi, New Delhi", "Respondent": "ACIT, Circle- 61(1), New Delhi", "Bench": "C", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 86/DEL/2020", "Filed By": "Department", "Appellant": "ACIT, Range-1, Gurgaon", "Respondent": "Jindal Steel & Power Ltd., New Delhi", "Bench": "C", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 9528/DEL/2019", "Filed By": "Assessee", "Appellant": "Maa Sharda Educational Society, Ghaziabad", "Respondent": "ITO, Exemtption Ward, Ghaziabad", "Bench": "E", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 5574/DEL/2018", "Filed By": "Department", "Appellant": "ACIT, Circle-26(1), New Delhi", "Respondent": "Vakil Housing Developers Corporation P.Ltd, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 5718/DEL/2019", "Filed By": "Assessee", "Appellant": "Ratnashri Buildtech Pvt Ltd., Delhi", "Respondent": "ACIT Central Cicrle 4, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 5719/DEL/2019", "Filed By": "Assessee", "Appellant": "Ratna Talwar, Delhi", "Respondent": "ACIT, Central Circle- 4, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 5720/DEL/2019", "Filed By": "Assessee", "Appellant": "Ratna Talwar, Delhi", "Respondent": "ACIT, Central Circle- 4, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 5721/DEL/2019", "Filed By": "Assessee", "Appellant": "Ratna Talwar, Delhi", "Respondent": "ACIT, Central Circle- 4, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 5722/DEL/2019", "Filed By": "Assessee", "Appellant": "Ratna Talwar, Delhi", "Respondent": "ACIT, Central Circle- 4, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 7756/DEL/2019", "Filed By": "Assessee", "Appellant": "Pawan Arya, Delhi", "Respondent": "ACIT, Central Circle- 25, New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 7759/DEL/2019", "Filed By": "Department", "Appellant": "ACIT, Central Circle- 25, New Delhi", "Respondent": "Pawan Arya, Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 8266/DEL/2019", "Filed By": "Assessee", "Appellant": "Roop Kishore Agarwal (HUF), Delhi", "Respondent": "ITO ward-46(2), New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 8289/DEL/2019", "Filed By": "Assessee", "Appellant": "Rajni Garg, Gurgaon", "Respondent": "ITO WARD - 44(5), New Delhi", "Bench": "F", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 4780/DEL/2019", "Filed By": "Assessee", "Appellant": "Green Village Agros Pvt Ltd, Karnal", "Respondent": "PCIT, Karnal", "Bench": "G", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 9756/DEL/2019", "Filed By": "Department", "Appellant": "ACIT circle-25(2), New Delhi", "Respondent": "TV Today Network Ltd., New Delhi", "Bench": "G", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 187/DEL/2022", "Filed By": "Assessee", "Appellant": "Tarsem Lal Verma , Haryana", "Respondent": "Circle 66(1), Delhi", "Bench": "G", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 6537/DEL/2019", "Filed By": "Assessee", "Appellant": "Drishti India Ltd, New Delhi", "Respondent": "ITO WARD - 7(4), New Delhi", "Bench": "SMC", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 594/DEL/2019", "Filed By": "Department", "Appellant": "ITO, Ward-1(1), Noida", "Respondent": "Ashok Kumar, Noida", "Bench": "SMC", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 149/CTK/2014", "Filed By": "Assessee", "Appellant": "Tata Spone Iron Ltd, Keonjhar", "Respondent": "JCIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 158/CTK/2014", "Filed By": "Department", "Appellant": "ACIT, Bhubaneswar", "Respondent": "Tata Spone Iron Ltd, Keonjhar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 115/CTK/2015", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 117/CTK/2015", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 116/CTK/2015", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "CIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 152/CTK/2015", "Filed By": "Department", "Appellant": "ACIT, Bhubaneswar", "Respondent": "M/s. Tata Sponge Iron Limited, Keonjhar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 153/CTK/2015", "Filed By": "Department", "Appellant": "ACIT, Bhubaneswar", "Respondent": "M/s. Tata Sponge Iron Limited, Keonjhar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 407/CTK/2015", "Filed By": "Department", "Appellant": "ACIT, Bhubaneswar", "Respondent": "M/s. Tata Sponge Iron Limited, Keonjhar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 416/CTK/2015", "Filed By": "Assessee", "Appellant": "M/s. Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 103/CTK/2016", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Circle-1(2), Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 104/CTK/2016", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Circle-1(2), Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 116/CTK/2016", "Filed By": "Department", "Appellant": "ACIT, Corporate Circle-1(2), Bhubaneswar", "Respondent": "M/s. Tata Sponge Iron Limited, Keonjhar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 169/CTK/2017", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Circle-1(2), Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 168/CTK/2017", "Filed By": "Assessee", "Appellant": "Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Circle-1(2), Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 117/CTK/2016", "Filed By": "Department", "Appellant": "ACIT, Corporate Circle-1(2), Bhubaneswar", "Respondent": "Tata Sponge Iron Limited, Keonjhar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "CO 32/CTK/2014", "Filed By": "Assessee", "Appellant": "M/s. Tata Sponge Iron Ltd., Keonjhar", "Respondent": "JCIT, Range-2, Bhubaneswar, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "CO 18/CTK/2015", "Filed By": "Assessee", "Appellant": "M/s. Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "CO 19/CTK/2015", "Filed By": "Assessee", "Appellant": "M/s. Tata Sponge Iron Limited, Keonjhar", "Respondent": "ACIT, Bhubaneswar", "Bench": "DB", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITTPA 1/CHNY/2021", "Filed By": "Assessee", "Appellant": "VERIZON COMMUNICATIONS SINGAPORE PTE LTD., SINGAPORE", "Respondent": "DCIT, INTNL TAXATION-1(2), CHENNAI", "Bench": "D", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1095/CHNY/2017", "Filed By": "Assessee", "Appellant": "Col. D.Pradeep Kumar, CHENNAI", "Respondent": "DCIT, CHENNAI", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 633/CHNY/2020", "Filed By": "Assessee", "Appellant": "LEMMINKAINEN CONSTRUCTION (I) P LTD, CHENNAI", "Respondent": "ACIT CORPORATE CIRCLE-4(1), CHENNAI", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 37/CHNY/2020", "Filed By": "Assessee", "Appellant": "PRAVEEN KUMAR JAIN HUF, CHENNAI", "Respondent": "ITO NON CORPORATE WARD-5(4), CHENNAI", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 41/CHNY/2020", "Filed By": "Assessee", "Appellant": "Jayanthilal, CHENNAI", "Respondent": "ITO Non Corporate Ward 4(2), CHENNAI", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 295/CHNY/2019", "Filed By": "Assessee", "Appellant": "SARAVANA FOUNDATION, CHENNAI", "Respondent": "ITO, NCW-15(4), CHENNAI", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 66/CHNY/2020", "Filed By": "Assessee", "Appellant": "M.Ramamurthy, Hosur", "Respondent": "DCIT Central Circle 1, Coimbatore", "Bench": "C", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 67/CHNY/2020", "Filed By": "Assessee", "Appellant": "M.Ramamurthy, Hosur", "Respondent": "DCIT Central Circle 1, Coimbatore", "Bench": "C", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 68/CHNY/2020", "Filed By": "Assessee", "Appellant": "M.Ramamurthy, Hosur", "Respondent": "DCIT Central Circle 1, Coimbatore", "Bench": "C", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "MA 9/CHNY/2022", "Filed By": "Assessee", "Appellant": "Ravi Kumar Distilleries Ltd., Pondicherry", "Respondent": "DCIT Pondicherry Circle , Pondicherry", "Bench": "D", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1305/CHANDI/2018", "Filed By": "Assessee", "Appellant": "M/s Gymkhana Club, Panchkula", "Respondent": "ITO, W-3, Panchkula", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 917/CHANDI/2019", "Filed By": "Assessee", "Appellant": "M/s Haryana Agro Industries Corporation Ltd., Panchkula", "Respondent": "ACIT, Circle, Panchkula", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 918/CHANDI/2019", "Filed By": "Assessee", "Appellant": "M/s Haryana Agro Industries Corporation Ltd., Panchkula", "Respondent": "DCIT, Circle, Panchkula", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 919/CHANDI/2019", "Filed By": "Assessee", "Appellant": "M/s Haryana Agro Industries Corporation Ltd., Panchkula", "Respondent": "ACIT, Circle, Panchkula", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 920/CHANDI/2019", "Filed By": "Assessee", "Appellant": "M/s Haryana Agro Industries Corporation Ltd., Panchkula", "Respondent": "DCIT, Circle, Panchkula", "Bench": "A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 335/CHANDI/2020", "Filed By": "Assessee", "Appellant": "Sri Shwetambar Jain Education Society, Panipat", "Respondent": "CIT(E), Chandgarh", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 103/AHD/2021", "Filed By": "Assessee", "Appellant": "Atul Club Trust, Valsad", "Respondent": "The CIT (Exemption), Ahmedabad", "Bench": "B", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1039/Hyd/2018", "Filed By": "Department", "Appellant": "Asst. Commissioner of Income Tax, Circle-1, Kurnool", "Respondent": "Panyam Cements & Mineral Industries Limited, Nandyal", "Bench": "DB-A", "Case Status": "Disposed", "Details": ""}
{"Appeal Number": "ITA 1963/Hyd/2018", "Filed By": "Department", "Appellant": "Asst. Commissioner of Income Tax, Circle-1, Kurnool", "Respondent": "Panyam Cement & Mineral Industris Limited , Nandyal", "Bench": "DB-A", "Case Status": "Disposed", "Details": ""}
